"""
tools/pr_opener.py — Opens GitHub Pull Requests with review findings.
Requires GITHUB_TOKEN with repo + pull_requests scopes.
In DRY_RUN mode: prints the PR body instead of opening.
"""

from __future__ import annotations
from pathlib import Path
from typing import Optional
import requests
from rich.console import Console

from config import EnvConfig, RepoReview, FileReview, SEVERITY_EMOJI, CATEGORY_EMOJI

console = Console()

GITHUB_API = "https://api.github.com"


def open_review_pr(
    review: RepoReview,
    refactored_files: list[Path],
    branch_name: str = "ai-code-review",
) -> Optional[str]:
    """
    Open a GitHub PR with the review findings.
    Returns the PR URL, or None if dry run / failed.
    """
    if EnvConfig.DRY_RUN:
        _print_dry_run_pr(review)
        return None

    if not EnvConfig.GITHUB_TOKEN:
        console.print("[yellow]No GITHUB_TOKEN set — skipping PR creation.[/yellow]")
        return None

    owner, repo = _parse_owner_repo(review.repo_url)
    if not owner or not repo:
        console.print("[red]Could not parse owner/repo from URL.[/red]")
        return None

    headers = {
        "Authorization": f"Bearer {EnvConfig.GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    # Get default branch
    default_branch = _get_default_branch(owner, repo, headers)

    # Create review branch
    base_sha = _get_branch_sha(owner, repo, default_branch, headers)
    if not base_sha:
        console.print("[red]Could not get base branch SHA.[/red]")
        return None

    created = _create_branch(owner, repo, branch_name, base_sha, headers)
    if not created:
        console.print(f"[yellow]Branch '{branch_name}' may already exist — continuing.[/yellow]")

    # Commit refactored files
    committed = 0
    for fpath in refactored_files:
        content = fpath.read_text(encoding="utf-8")
        original_path = fpath.name.replace("__", "/")
        ok = _commit_file(owner, repo, branch_name, original_path, content, headers)
        if ok:
            committed += 1

    # Open PR
    pr_body = _build_pr_body(review)
    pr_title = f"🤖 AI Code Review — {review.critical_count} critical, {review.high_count} high issues found"

    pr_url = _create_pr(owner, repo, pr_title, pr_body, branch_name, default_branch, headers)

    if pr_url:
        console.print(f"[green]✓ PR opened:[/green] {pr_url}")
    return pr_url


def _build_pr_body(review: RepoReview) -> str:
    lines = [
        f"## 🤖 Automated Code Review",
        f"",
        f"This PR was opened by the [AI Code Review Agent](https://github.com/EnggTalha/ai-code-review-agent).",
        f"",
        f"### 📊 Summary",
        f"",
        f"| Metric | Value |",
        f"|---|---|",
        f"| Overall Score | {review.overall_score}/100 |",
        f"| Files Reviewed | {review.reviewed_files} |",
        f"| 🔴 Critical | {review.critical_count} |",
        f"| 🟠 High | {review.high_count} |",
        f"| 🟡 Medium | {review.medium_count} |",
        f"| 🟢 Low | {review.low_count} |",
        f"",
        f"### 🧠 Executive Summary",
        f"",
        review.executive_summary,
        f"",
        f"### 🚨 Top Issues",
        f"",
    ]

    for i, issue in enumerate(review.top_issues[:5], 1):
        sev = SEVERITY_EMOJI.get(issue.severity, "⚪")
        lines += [
            f"**{i}. {sev} {issue.title}**  ",
            f"`{issue.file}` line {issue.line_start} — {issue.description}",
            f"",
        ]

    lines += [
        f"---",
        f"*Review generated by Claude (Anthropic) — please verify all suggestions before merging.*",
    ]
    return "\n".join(lines)


def _print_dry_run_pr(review: RepoReview) -> None:
    console.print("\n[bold yellow][DRY RUN] PR that would be opened:[/bold yellow]")
    console.print(f"Title: 🤖 AI Code Review — {review.critical_count} critical, {review.high_count} high issues")
    console.print(f"Branch: ai-code-review → main")
    console.print(_build_pr_body(review))


# ── GitHub API helpers ─────────────────────────────────────────────────

def _get_default_branch(owner: str, repo: str, headers: dict) -> str:
    try:
        r = requests.get(f"{GITHUB_API}/repos/{owner}/{repo}", headers=headers, timeout=10)
        return r.json().get("default_branch", "main")
    except Exception:
        return "main"


def _get_branch_sha(owner: str, repo: str, branch: str, headers: dict) -> Optional[str]:
    try:
        r = requests.get(
            f"{GITHUB_API}/repos/{owner}/{repo}/git/ref/heads/{branch}",
            headers=headers, timeout=10,
        )
        return r.json()["object"]["sha"]
    except Exception:
        return None


def _create_branch(owner: str, repo: str, branch: str, sha: str, headers: dict) -> bool:
    try:
        r = requests.post(
            f"{GITHUB_API}/repos/{owner}/{repo}/git/refs",
            headers=headers,
            json={"ref": f"refs/heads/{branch}", "sha": sha},
            timeout=10,
        )
        return r.status_code == 201
    except Exception:
        return False


def _commit_file(owner: str, repo: str, branch: str, path: str, content: str, headers: dict) -> bool:
    import base64
    try:
        encoded = base64.b64encode(content.encode()).decode()
        r = requests.put(
            f"{GITHUB_API}/repos/{owner}/{repo}/contents/{path}",
            headers=headers,
            json={
                "message": f"refactor: AI code review suggestions for {path}",
                "content": encoded,
                "branch": branch,
            },
            timeout=15,
        )
        return r.status_code in (200, 201)
    except Exception:
        return False


def _create_pr(owner: str, repo: str, title: str, body: str, head: str, base: str, headers: dict) -> Optional[str]:
    try:
        r = requests.post(
            f"{GITHUB_API}/repos/{owner}/{repo}/pulls",
            headers=headers,
            json={"title": title, "body": body, "head": head, "base": base},
            timeout=15,
        )
        return r.json().get("html_url")
    except Exception:
        return None


def _parse_owner_repo(url: str) -> tuple[str, str]:
    url = url.rstrip("/").rstrip(".git")
    parts = url.split("/")
    if len(parts) >= 2:
        return parts[-2], parts[-1]
    return "", ""
