"""
tools/reporter.py — Generates beautiful Markdown and HTML review reports.
Also saves refactored files as patch-ready outputs.
"""

from __future__ import annotations
import json
from datetime import datetime
from pathlib import Path
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich import box

from config import RepoReview, FileReview, CodeIssue, REPORTS_DIR, PATCHES_DIR

console = Console()

SEVERITY_EMOJI = {
    "critical": "🔴",
    "high":     "🟠",
    "medium":   "🟡",
    "low":      "🟢",
}

CATEGORY_EMOJI = {
    "bug":           "🐛",
    "security":      "🔒",
    "performance":   "⚡",
    "style":         "✨",
    "refactor":      "♻️",
    "documentation": "📝",
}


# ── Markdown report ────────────────────────────────────────────────────

def generate_markdown_report(review: RepoReview) -> Path:
    """Generate a full Markdown report for the repo review."""
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = REPORTS_DIR / f"{review.repo_name}_{ts}.md"

    lines = []

    # Header
    lines += [
        f"# 🤖 AI Code Review Report",
        f"",
        f"**Repository:** [{review.repo_url}]({review.repo_url})  ",
        f"**Reviewed:** {datetime.now().strftime('%B %d, %Y at %H:%M')}  ",
        f"**Files reviewed:** {review.reviewed_files} / {review.total_files}  ",
        f"**Overall Score:** {_score_badge(review.overall_score)}",
        f"",
        f"---",
        f"",
    ]

    # Summary scorecard
    lines += [
        f"## 📊 Issue Summary",
        f"",
        f"| Severity | Count |",
        f"|---|---|",
        f"| 🔴 Critical | {review.critical_count} |",
        f"| 🟠 High | {review.high_count} |",
        f"| 🟡 Medium | {review.medium_count} |",
        f"| 🟢 Low | {review.low_count} |",
        f"| **Total** | **{review.critical_count + review.high_count + review.medium_count + review.low_count}** |",
        f"",
        f"---",
        f"",
    ]

    # Executive summary
    lines += [
        f"## 🧠 Executive Summary",
        f"",
        review.executive_summary,
        f"",
        f"---",
        f"",
    ]

    # Top issues
    if review.top_issues:
        lines += [f"## 🚨 Top Issues", f""]
        for i, issue in enumerate(review.top_issues, 1):
            sev_emoji = SEVERITY_EMOJI.get(issue.severity, "⚪")
            cat_emoji = CATEGORY_EMOJI.get(issue.category, "🔧")
            lines += [
                f"### {i}. {sev_emoji} {issue.title}",
                f"",
                f"- **File:** `{issue.file}` (lines {issue.line_start}–{issue.line_end})",
                f"- **Severity:** `{issue.severity.upper()}` | **Category:** {cat_emoji} `{issue.category}`",
                f"- **Problem:** {issue.description}",
                f"- **Fix:** {issue.suggestion}",
                f"",
            ]
            if issue.code_before and issue.code_after:
                lines += [
                    f"**Before:**",
                    f"```",
                    issue.code_before.strip(),
                    f"```",
                    f"",
                    f"**After:**",
                    f"```",
                    issue.code_after.strip(),
                    f"```",
                    f"",
                ]
        lines += [f"---", f""]

    # Per-file breakdown
    lines += [f"## 📁 File-by-File Breakdown", f""]
    for fr in sorted(review.file_reviews, key=lambda x: x.overall_score):
        lines += [
            f"### `{fr.file_path}` — Score: {_score_badge(fr.overall_score)}",
            f"",
            f"**Language:** {fr.language} | **Lines of code:** {fr.lines_of_code}  ",
            f"**Summary:** {fr.summary}",
            f"",
        ]
        if fr.issues:
            lines += [
                f"| # | Severity | Category | Line | Title |",
                f"|---|---|---|---|---|",
            ]
            for issue in fr.issues:
                sev = SEVERITY_EMOJI.get(issue.severity, "⚪") + f" `{issue.severity}`"
                cat = CATEGORY_EMOJI.get(issue.category, "🔧") + f" {issue.category}"
                lines.append(
                    f"| | {sev} | {cat} | {issue.line_start} | {issue.title} |"
                )
            lines.append("")
        else:
            lines += [f"✅ No issues found in this file.", f""]

    # Footer
    lines += [
        f"---",
        f"",
        f"*Generated by [AI Code Review Agent](https://github.com/EnggTalha/ai-code-review-agent) "
        f"powered by [Claude](https://anthropic.com)*",
    ]

    out_path.write_text("\n".join(lines), encoding="utf-8")
    console.print(f"[green]✓[/green] Markdown report → {out_path}")
    return out_path


# ── JSON report ────────────────────────────────────────────────────────

def save_json_report(review: RepoReview) -> Path:
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = REPORTS_DIR / f"{review.repo_name}_{ts}.json"
    with open(out_path, "w") as f:
        json.dump(review.model_dump(), f, indent=2, default=str)
    console.print(f"[green]✓[/green] JSON report → {out_path}")
    return out_path


# ── Save refactored files ──────────────────────────────────────────────

def save_refactored_files(review: RepoReview) -> list[Path]:
    """Save refactored versions of files that Claude rewrote."""
    saved = []
    for fr in review.file_reviews:
        if fr.refactored_code and fr.refactored_code.strip():
            out_dir = PATCHES_DIR / review.repo_name
            out_dir.mkdir(parents=True, exist_ok=True)
            safe_name = fr.file_path.replace("/", "__").replace("\\", "__")
            out_path = out_dir / safe_name
            out_path.write_text(fr.refactored_code, encoding="utf-8")
            saved.append(out_path)

    if saved:
        console.print(f"[green]✓[/green] {len(saved)} refactored files saved → {PATCHES_DIR / review.repo_name}")
    return saved


# ── Rich terminal summary ──────────────────────────────────────────────

def print_terminal_summary(review: RepoReview) -> None:
    """Print a beautiful Rich summary table to the terminal."""
    console.print()
    console.print(
        Panel.fit(
            f"[bold]AI Code Review — {review.repo_name}[/bold]\n"
            f"Score: [{'green' if review.overall_score >= 70 else 'yellow' if review.overall_score >= 50 else 'red'}]"
            f"{review.overall_score}/100[/]\n"
            f"🔴 {review.critical_count} critical  "
            f"🟠 {review.high_count} high  "
            f"🟡 {review.medium_count} medium  "
            f"🟢 {review.low_count} low",
            border_style="cyan",
        )
    )

    if review.top_issues:
        table = Table(
            title="Top Issues",
            box=box.ROUNDED,
            border_style="cyan",
            show_lines=True,
        )
        table.add_column("Severity", justify="center", width=10)
        table.add_column("Category", width=12)
        table.add_column("File", max_width=30)
        table.add_column("Line", justify="center", width=6)
        table.add_column("Issue", max_width=40)

        for issue in review.top_issues[:8]:
            sev_color = {"critical": "red", "high": "orange3", "medium": "yellow", "low": "green"}.get(issue.severity, "white")
            table.add_row(
                f"[{sev_color}]{issue.severity.upper()}[/{sev_color}]",
                issue.category,
                issue.file.split("/")[-1],
                str(issue.line_start),
                issue.title,
            )
        console.print(table)

    console.print(f"\n[bold]Executive Summary:[/bold]\n{review.executive_summary}\n")


# ── Helpers ────────────────────────────────────────────────────────────

def _score_badge(score: int) -> str:
    if score >= 80:
        return f"🟢 **{score}/100**"
    elif score >= 60:
        return f"🟡 **{score}/100**"
    elif score >= 40:
        return f"🟠 **{score}/100**"
    else:
        return f"🔴 **{score}/100**"
